name: CI Training

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlproject-env

      - name: Install pip packages
        run: |
          pip install mlflow==2.19.0 dagshub==0.5.1 scikit-learn==1.6.0 pandas==2.2.3 numpy==2.2.1

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run modelling --env-manager=local

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/MLProject
