name: CI Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/processed.csv"
  TARGET_VAR: "target"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow  
          
      # Run as a mlflow project
      - name: Run mlflow project
        working-directory: ./MLProject
        run: |
          mlflow run . --env-manager=local 

      
      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ./MLProject/mlruns

      # - name: Build Docker image
      #   run: |
      #     mlflow models build-docker -m ./MLProject/mlruns/0/$RUN_ID/artifacts/model -n churn-model:latest
      
      # - name: Login to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Push Docker image
      #   run: docker tag churn-model:latest ${{ secrets.DOCKER_USERNAME }}/churn-model:latest && docker push ${{ secrets.DOCKER_USERNAME }}/churn-model:latest

